version: '2'
services:
  redis-cluster:
    #images: registry.docker-cn.com/grokzen/redis-cluster:4.0.9
    environment:
     IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      args:
        redis_version: '3.2.11'
    hostname: server
    ports:
      - '7000-7007:7000-7007'
